FROM denoland/deno:2.3.3

RUN apt-get update && apt-get install -y --no-install-recommends \
      git curl wget unzip bash-completion ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=1000

RUN groupadd --gid $USER_GID $USERNAME \
 && useradd  --uid $USER_UID --gid $USER_GID -m -s /bin/bash $USERNAME \
 && mkdir -p /home/$USERNAME/.cache/deno \
 && chown -R $USERNAME:$USERNAME /home/$USERNAME

USER $USERNAME

ENV DENO_DIR=/home/vscode/.cache/deno

WORKDIR /workspace